<?php

namespace LibraryBundle\Repository;

/**
 * PublishersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublishersRepository extends \Doctrine\ORM\EntityRepository
{
}
